// Code generated by protoc-gen-go. DO NOT EDIT.
// source: main.proto

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	main.proto

It has these top-level messages:
	Structure1
	Structure2
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Structure1 struct {
	Field1 string               `protobuf:"bytes,1,opt,name=field1" json:"field1,omitempty"`
	Field2 *google_protobuf.Any `protobuf:"bytes,2,opt,name=field2" json:"field2,omitempty"`
	Field3 string               `protobuf:"bytes,3,opt,name=field3" json:"field3,omitempty"`
}

func (m *Structure1) Reset()                    { *m = Structure1{} }
func (m *Structure1) String() string            { return proto.CompactTextString(m) }
func (*Structure1) ProtoMessage()               {}
func (*Structure1) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Structure1) GetField1() string {
	if m != nil {
		return m.Field1
	}
	return ""
}

func (m *Structure1) GetField2() *google_protobuf.Any {
	if m != nil {
		return m.Field2
	}
	return nil
}

func (m *Structure1) GetField3() string {
	if m != nil {
		return m.Field3
	}
	return ""
}

type Structure2 struct {
	Field1 string               `protobuf:"bytes,1,opt,name=field1" json:"field1,omitempty"`
	Field2 string               `protobuf:"bytes,2,opt,name=field2" json:"field2,omitempty"`
	Field3 *google_protobuf.Any `protobuf:"bytes,3,opt,name=field3" json:"field3,omitempty"`
}

func (m *Structure2) Reset()                    { *m = Structure2{} }
func (m *Structure2) String() string            { return proto.CompactTextString(m) }
func (*Structure2) ProtoMessage()               {}
func (*Structure2) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Structure2) GetField1() string {
	if m != nil {
		return m.Field1
	}
	return ""
}

func (m *Structure2) GetField2() string {
	if m != nil {
		return m.Field2
	}
	return ""
}

func (m *Structure2) GetField3() *google_protobuf.Any {
	if m != nil {
		return m.Field3
	}
	return nil
}

func init() {
	proto.RegisterType((*Structure1)(nil), "Structure1")
	proto.RegisterType((*Structure2)(nil), "Structure2")
}

func init() { proto.RegisterFile("main.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x4d, 0xcc, 0xcc,
	0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0x92, 0x4c, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07,
	0xf3, 0x92, 0x4a, 0xd3, 0xf4, 0x13, 0xf3, 0x2a, 0x21, 0x52, 0x4a, 0x59, 0x5c, 0x5c, 0xc1, 0x25,
	0x45, 0xa5, 0xc9, 0x25, 0xa5, 0x45, 0xa9, 0x86, 0x42, 0x62, 0x5c, 0x6c, 0x69, 0x99, 0xa9, 0x39,
	0x29, 0x86, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x50, 0x9e, 0x90, 0x0e, 0x54, 0xdc, 0x48,
	0x82, 0x49, 0x81, 0x51, 0x83, 0xdb, 0x48, 0x44, 0x0f, 0x62, 0xa2, 0x1e, 0xcc, 0x44, 0x3d, 0xc7,
	0xbc, 0x4a, 0xa8, 0x6a, 0x23, 0xb8, 0x29, 0xc6, 0x12, 0xcc, 0x48, 0xa6, 0x18, 0xa3, 0xd8, 0x65,
	0x84, 0xd3, 0x2e, 0x31, 0x14, 0xbb, 0x38, 0xe1, 0xa6, 0xea, 0xa0, 0x98, 0x8a, 0xdf, 0x0d, 0xc6,
	0x49, 0x6c, 0x60, 0x51, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf7, 0x12, 0xab, 0x83, 0x07,
	0x01, 0x00, 0x00,
}
